version: '2'
services:
    jhipstersampleapplicationws-app:
        image: jhipstersampleapplicationws
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplicationws-mysql:3306/jhipstersampleapplicationws?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplicationws-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplicationws-mysql
